site_name: voidpdev
site_url: https://voidp.dev/
# repo_url: https://github.com/Samandar-Komilov/
copyright: Copyright &copy; 2025 - 2026 Samandar Komil
theme:
  name: material
  icon:
    logo: simple/voipdotms
    tag:
      rust: fontawesome/brands/rust
  favicon: assets/voidp_circle.png
  language: en
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: green
      accent: lime
  font:
    text: Roboto
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.footer
    - navigation.indexes
    - search.highlight
    # - navigation.tabs

extra:
  tags:
    Rust: rust
    C: c
    AI assisted: ai
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/voidplog
    - icon: fontawesome/brands/github
      link: https://github.com/Samandar-Komilov
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/SamandarKomil
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/samandar_komilov
  generator: false

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Projects:
      - projects/index.md
      - Ideas: projects/ideas.md
      - CServe: projects/cserve.md
      - Oberoon: projects/oberoon.md
      - Gira: projects/gira.md
  - Blog: blog/index.md
  - Tags: tags.md


plugins:
  - blog:
      pagination_per_page: 5
      pagination_if_single_page: true
  - tags
  - search
  - social


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg