site_name: voidpdev
site_url: https://voidp.dev/
repo_url: https://github.com/Samandar-Komilov/
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: green
      accent: lime
  font:
    text: Roboto
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - About: about.md
  - Projects:
      - Overview: projects/overview.md
      - Nginx Clone: 
        - About: projects/nginx_clone/nginx_clone.md
        - Journey: projects/nginx_clone/journey.md
      - URL Shortener: 
        - About: projects/url_shortener/url_shortener.md
        - Strategy: projects/url_shortener/strategy.md
      - WSGI Framework: projects/oberoon.md
  - Blog: blog/index.md


plugins:
  - blog:
      pagination_per_page: 5
      pagination_if_single_page: true
  - search
  - social


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences