site_name: voidpdev
site_url: https://voidp.dev/
# repo_url: https://github.com/Samandar-Komilov/
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: green
      accent: lime
  font:
    text: Roboto
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.footer

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Projects:
      - Overview: projects/overview.md
      - Nginx Clone: 
        - About: projects/nginx_clone/nginx_clone.md
        - Journey: projects/nginx_clone/journey.md
      - URL Shortener: 
        - About: projects/url_shortener/url_shortener.md
        - In-memory Service: projects/url_shortener/v1.md
        - DB Persistency: projects/url_shortener/v2.md
        - Shortcode Generation: projects/url_shortener/v3.md
        - Caching: projects/url_shortener/v4.md
        - Rate Limiting: projects/url_shortener/v5.md
        - Analytics: projects/url_shortener/v6.md
        - Vertical Scaling: projects/url_shortener/v7.md
        - Horizontal Scaling: projects/url_shortener/v8.md
      - WSGI Framework: 
        - About: projects/oberoon/oberoon.md
  - Research:
    - C Patterns:
      - Error Handling: research/c_patterns/error_handling.md
      - Memory Management: research/c_patterns/memory_management.md
    - Network Programming:
      - Beej's Guide Reference: research/networkp/beejs_reference.md
  - Blog: blog/index.md


plugins:
  - blog:
      pagination_per_page: 5
      pagination_if_single_page: true
  - search
  - social


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg