site_name: voidpdev
site_url: https://voidp.dev/
# repo_url: https://github.com/Samandar-Komilov/
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: green
      accent: lime
  font:
    text: Roboto
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.footer
    # - navigation.tabs

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Projects:
      - Overview: projects/overview.md
      - Ideas: projects/ideas/overview.md
      - CServe: 
        - About: projects/cserve/cserve.md
        - Journey: projects/cserve/journey.md
      - Oberoon: 
        - About: projects/oberoon/oberoon.md
      - Gira: 
        - About: projects/gira/gira.md
  - Research:
    - C Language:
      - Network Programming: research/clang/beejs_reference.md
      - Memory Management Patterns: research/clang/memory_management.md
      - Error Handling Patterns: research/clang/error_handling.md
    - Go Language:
      - Path: research/golang/path.md
    - Rust Language:
      - Common Concepts: research/rust/common_concepts.md
      - Ownership and Borrowing: research/rust/ownership_borrowing.md
    - Linux:
      - Big Picture and Basic Commands: research/linux/big_picture_basic_commands.md
      - How Linux Kernel Boots: research/linux/how_kernel_boots.md
    - System Design:
      - URL Shortener: research/system_design/url_shortener.md
    - Discrete Math:
      - Definitions: research/discrete_math/definitions.md
  - Blog: blog/index.md


plugins:
  - blog:
      pagination_per_page: 5
      pagination_if_single_page: true
  - search
  - social


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg